## Name of the workflow
name: Cypress Component Tests

## On pull request from following branches
on:
  pull_request:
    branches:
      - develop
      - featureTesting

## jobs to be completed
jobs:
  cypress:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm i

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          build: npm run build
          start: npm run start
          component: true


# jobs:
#   ## Cypress on operating systems and 3 different node versions to test
#   cypress:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: npm install

#       - name: Cypress
#         uses: cypress-io/github-action@v6
#         with: 
#           build: npm run build
#           start: npm run start
#           component: true