## Name of the workflow
name: Cypress Component Tests

## On pull request from following branches
on:
  pull_request:
    branches:
      - develop
      - featureTesting

## jobs to be completed
jobs:
  ## Cypress on operating systems and 3 different node versions to test
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v6
        with: 
          build: npm run build
          start: npm run start
          component: true